<?php

declare(strict_types=1);

namespace DB\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20211021115148 extends AbstractMigration
{
    public function getDescription() : string
    {
        return '';
    }

    public function up(Schema $schema) : void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('ALTER TABLE address CHANGE main main TINYINT(1) NOT NULL');
        $this->addSql('ALTER TABLE article CHANGE article_category_id article_category_id INT UNSIGNED DEFAULT NULL COMMENT \'Primární klíč\', CHANGE created_user_id created_user_id INT UNSIGNED DEFAULT NULL COMMENT \'id\', CHANGE changed_user_id changed_user_id INT UNSIGNED DEFAULT NULL COMMENT \'id\', CHANGE active active TINYINT(1) DEFAULT \'1\' NOT NULL COMMENT \'Platný\', CHANGE not_deleted not_deleted TINYINT(1) DEFAULT \'1\' COMMENT \'Nesmazaný\'');
        $this->addSql('ALTER TABLE article_category CHANGE article_category_id article_category_id INT UNSIGNED DEFAULT NULL COMMENT \'Primární klíč\', CHANGE created_user_id created_user_id INT UNSIGNED DEFAULT NULL COMMENT \'id\', CHANGE changed_user_id changed_user_id INT UNSIGNED DEFAULT NULL COMMENT \'id\', CHANGE active active TINYINT(1) DEFAULT \'1\' NOT NULL COMMENT \'Platný\', CHANGE not_deleted not_deleted TINYINT(1) DEFAULT \'1\' COMMENT \'Nesmazaný\'');
        $this->addSql('ALTER TABLE article_tag DROP FOREIGN KEY article_tag_article_id');
        $this->addSql('ALTER TABLE article_tag DROP FOREIGN KEY article_tag_tag_id');
        $this->addSql('ALTER TABLE article_tag CHANGE article_id article_id INT UNSIGNED DEFAULT NULL COMMENT \'Primární klíč\', CHANGE tag_id tag_id INT UNSIGNED DEFAULT NULL COMMENT \'Primární klíč\', CHANGE not_deleted not_deleted TINYINT(1) DEFAULT \'1\' COMMENT \'Nesmazaný\'');
        $this->addSql('ALTER TABLE article_tag ADD CONSTRAINT FK_919694F97294869C FOREIGN KEY (article_id) REFERENCES article (id)');
        $this->addSql('ALTER TABLE article_tag ADD CONSTRAINT FK_919694F9BAD26311 FOREIGN KEY (tag_id) REFERENCES tag (id)');
        $this->addSql('ALTER TABLE author CHANGE image_file_id image_file_id INT UNSIGNED DEFAULT NULL COMMENT \'Id\', CHANGE created_user_id created_user_id INT UNSIGNED DEFAULT NULL COMMENT \'id\', CHANGE changed_user_id changed_user_id INT UNSIGNED DEFAULT NULL COMMENT \'id\', CHANGE active active TINYINT(1) DEFAULT \'1\' NOT NULL COMMENT \'Platný\', CHANGE not_deleted not_deleted TINYINT(1) DEFAULT \'1\' COMMENT \'Nesmazaný\'');
        $this->addSql('ALTER TABLE author_in_product DROP FOREIGN KEY FK_author_in_product_author');
        $this->addSql('ALTER TABLE author_in_product DROP FOREIGN KEY FK_author_in_product_product');
        $this->addSql('ALTER TABLE author_in_product CHANGE author_id author_id INT UNSIGNED DEFAULT NULL COMMENT \'Id\', CHANGE product_id product_id INT UNSIGNED DEFAULT NULL COMMENT \'Id\', CHANGE not_deleted not_deleted TINYINT(1) DEFAULT \'1\'');
        $this->addSql('ALTER TABLE author_in_product ADD CONSTRAINT FK_DAF05BF8F675F31B FOREIGN KEY (author_id) REFERENCES author (id)');
        $this->addSql('ALTER TABLE author_in_product ADD CONSTRAINT FK_DAF05BF84584665A FOREIGN KEY (product_id) REFERENCES product (id)');
        $this->addSql('ALTER TABLE bank_code CHANGE created_user_id created_user_id INT UNSIGNED DEFAULT NULL COMMENT \'id\', CHANGE changed_user_id changed_user_id INT UNSIGNED DEFAULT NULL COMMENT \'id\', CHANGE active active TINYINT(1) DEFAULT \'1\' NOT NULL COMMENT \'Aktivní\', CHANGE not_deleted not_deleted TINYINT(1) DEFAULT \'1\' COMMENT \'Nesmazaný\'');
        $this->addSql('ALTER TABLE customer CHANGE state_id state_id SMALLINT UNSIGNED DEFAULT NULL COMMENT \'id\', CHANGE created_user_id created_user_id INT UNSIGNED DEFAULT NULL COMMENT \'id\', CHANGE changed_user_id changed_user_id INT UNSIGNED DEFAULT NULL COMMENT \'id\', CHANGE active active TINYINT(1) DEFAULT \'1\' NOT NULL COMMENT \'Platný\', CHANGE not_deleted not_deleted TINYINT(1) DEFAULT \'1\' COMMENT \'Nesmazaný\'');
        $this->addSql('ALTER TABLE customer2 CHANGE state_id state_id SMALLINT UNSIGNED DEFAULT NULL COMMENT \'id\', CHANGE active active TINYINT(1) DEFAULT \'1\' NOT NULL COMMENT \'Platný\', CHANGE not_deleted not_deleted TINYINT(1) DEFAULT \'1\' COMMENT \'Nesmazaný\'');
        $this->addSql('ALTER TABLE file CHANGE image image TINYINT(1) NOT NULL COMMENT \'Obrázek?\', CHANGE active active TINYINT(1) DEFAULT \'1\' NOT NULL COMMENT \'Platný\', CHANGE not_deleted not_deleted TINYINT(1) DEFAULT \'1\' COMMENT \'Nesmazaný\'');
        $this->addSql('ALTER TABLE help CHANGE not_deleted not_deleted TINYINT(1) DEFAULT \'1\' COMMENT \'Aktivní\'');
        $this->addSql('ALTER TABLE history CHANGE created_user_id created_user_id INT UNSIGNED DEFAULT NULL COMMENT \'id\', CHANGE not_deleted not_deleted TINYINT(1) DEFAULT \'1\' COMMENT \'Nesmazaný\'');
        $this->addSql('ALTER TABLE history_data DROP FOREIGN KEY history_data_ibfk_1');
        $this->addSql('ALTER TABLE history_data CHANGE history_id history_id BIGINT UNSIGNED DEFAULT NULL COMMENT \'id\'');
        $this->addSql('ALTER TABLE history_data ADD CONSTRAINT FK_A6C6831F1E058452 FOREIGN KEY (history_id) REFERENCES history (id)');
        $this->addSql('ALTER TABLE invoice CHANGE customer_id customer_id INT UNSIGNED DEFAULT NULL COMMENT \'id\', CHANGE paid paid TINYINT(1) NOT NULL COMMENT \'Zaplaceno\', CHANGE active active TINYINT(1) DEFAULT \'1\' NOT NULL COMMENT \'Platný\', CHANGE not_deleted not_deleted TINYINT(1) DEFAULT \'1\' COMMENT \'Nesmazaný\'');
        $this->addSql('ALTER TABLE invoice_delivery CHANGE invoice_id invoice_id INT UNSIGNED DEFAULT NULL COMMENT \'Id\', CHANGE active active TINYINT(1) DEFAULT \'1\' NOT NULL COMMENT \'Platný\', CHANGE not_deleted not_deleted TINYINT(1) DEFAULT \'1\' COMMENT \'Nesmazaný\'');
        $this->addSql('ALTER TABLE invoice_product CHANGE invoice_id invoice_id INT UNSIGNED DEFAULT NULL COMMENT \'Id\', CHANGE product_id product_id INT UNSIGNED DEFAULT NULL COMMENT \'Id\', CHANGE created_user_id created_user_id INT UNSIGNED DEFAULT NULL COMMENT \'id\', CHANGE active active TINYINT(1) DEFAULT \'1\' NOT NULL COMMENT \'Platný\', CHANGE not_deleted not_deleted TINYINT(1) DEFAULT \'1\' NOT NULL COMMENT \'Nesmazaný\'');
        $this->addSql('ALTER TABLE language CHANGE id id TINYINT(1) NOT NULL COMMENT \'Id\', CHANGE active active TINYINT(1) DEFAULT \'1\' NOT NULL COMMENT \'Platný\', CHANGE not_deleted not_deleted TINYINT(1) DEFAULT \'1\' COMMENT \'Nesmazaný\'');
        $this->addSql('ALTER TABLE login_log CHANGE user_id user_id INT UNSIGNED DEFAULT NULL COMMENT \'id\', CHANGE not_deleted not_deleted TINYINT(1) DEFAULT \'1\'');
        $this->addSql('ALTER TABLE message CHANGE sender_user_id sender_user_id INT UNSIGNED DEFAULT NULL COMMENT \'id\', CHANGE recipient_user_id recipient_user_id INT UNSIGNED DEFAULT NULL COMMENT \'id\', CHANGE `read` `read` TINYINT(1) NOT NULL COMMENT \'přečteno příjemcem\', CHANGE active active TINYINT(1) DEFAULT \'1\' NOT NULL COMMENT \'Aktivní\', CHANGE not_deleted not_deleted TINYINT(1) DEFAULT \'1\' COMMENT \'Nesmazaný\'');
        $this->addSql('ALTER TABLE notification CHANGE `read` `read` TINYINT(1) NOT NULL COMMENT \'přečteno příjemcem\', CHANGE active active TINYINT(1) DEFAULT \'1\' NOT NULL COMMENT \'Aktivní\', CHANGE not_deleted not_deleted TINYINT(1) DEFAULT \'1\' COMMENT \'Nesmazaný\'');
        $this->addSql('ALTER TABLE `order` CHANGE user_id user_id INT UNSIGNED DEFAULT NULL COMMENT \'id\', CHANGE shipping_id shipping_id INT UNSIGNED DEFAULT NULL COMMENT \'Id\', CHANGE payment_id payment_id INT UNSIGNED DEFAULT NULL COMMENT \'Id\', CHANGE shipping_address_id shipping_address_id INT UNSIGNED DEFAULT NULL COMMENT \'Id\', CHANGE invoice_address_id invoice_address_id INT UNSIGNED DEFAULT NULL COMMENT \'Id\', CHANGE created_user_id created_user_id INT UNSIGNED DEFAULT NULL COMMENT \'id\', CHANGE changed_user_id changed_user_id INT UNSIGNED DEFAULT NULL COMMENT \'id\'');
        $this->addSql('ALTER TABLE payment CHANGE online_payment online_payment TINYINT(1) DEFAULT NULL COMMENT \'Online platba\'');
        $this->addSql('ALTER TABLE product CHANGE product_category_id product_category_id INT UNSIGNED DEFAULT NULL COMMENT \'Id\', CHANGE language_id language_id TINYINT(1) DEFAULT NULL COMMENT \'Id\', CHANGE product_availability_id product_availability_id SMALLINT UNSIGNED DEFAULT NULL, CHANGE created_user_id created_user_id INT UNSIGNED DEFAULT NULL COMMENT \'id\', CHANGE changed_user_id changed_user_id INT UNSIGNED DEFAULT NULL COMMENT \'id\', CHANGE vat vat NUMERIC(4, 2) DEFAULT NULL COMMENT \'DPH\', CHANGE news news TINYINT(1) NOT NULL COMMENT \'Novinka\', CHANGE active active TINYINT(1) DEFAULT \'1\' NOT NULL COMMENT \'Platný\', CHANGE not_deleted not_deleted TINYINT(1) DEFAULT \'1\' COMMENT \'Nesmazaný\'');
        $this->addSql('ALTER TABLE product_category CHANGE product_category_id product_category_id INT UNSIGNED DEFAULT NULL COMMENT \'Id\', CHANGE created_user_id created_user_id INT UNSIGNED DEFAULT NULL COMMENT \'id\', CHANGE changed_user_id changed_user_id INT UNSIGNED DEFAULT NULL COMMENT \'id\', CHANGE active active TINYINT(1) DEFAULT \'1\' NOT NULL COMMENT \'Platný\', CHANGE not_deleted not_deleted TINYINT(1) DEFAULT \'1\' COMMENT \'Nesmazaný\'');
        $this->addSql('ALTER TABLE product_image CHANGE product_id product_id INT UNSIGNED DEFAULT NULL COMMENT \'Id\', CHANGE file_id file_id INT UNSIGNED DEFAULT NULL COMMENT \'Id\', CHANGE created_user_id created_user_id INT UNSIGNED DEFAULT NULL COMMENT \'id\', CHANGE changed_user_id changed_user_id INT UNSIGNED DEFAULT NULL COMMENT \'id\', CHANGE main main TINYINT(1) NOT NULL COMMENT \'Hlavní\', CHANGE active active TINYINT(1) DEFAULT \'1\' NOT NULL COMMENT \'Platný\', CHANGE not_deleted not_deleted TINYINT(1) DEFAULT \'1\' COMMENT \'Nesmazaný\'');
        $this->addSql('ALTER TABLE redirect CHANGE hits hits INT UNSIGNED NOT NULL COMMENT \'Počet použití\', CHANGE extra extra TINYINT(1) NOT NULL COMMENT \'Extra sitemap\'');
        $this->addSql('ALTER TABLE role CHANGE created_user_id created_user_id INT UNSIGNED DEFAULT NULL COMMENT \'id\', CHANGE changed_user_id changed_user_id INT UNSIGNED DEFAULT NULL COMMENT \'id\', CHANGE active active TINYINT(1) DEFAULT \'1\' NOT NULL COMMENT \'Platný\', CHANGE not_deleted not_deleted TINYINT(1) DEFAULT \'1\' COMMENT \'Nesmazaný\'');
        $this->addSql('ALTER TABLE rtgrid_state CHANGE id id VARCHAR(40) NOT NULL, CHANGE user_id user_id INT UNSIGNED NOT NULL');
        $this->addSql('ALTER TABLE settings CHANGE not_deleted not_deleted TINYINT(1) DEFAULT \'1\'');
        $this->addSql('ALTER TABLE state CHANGE not_deleted not_deleted TINYINT(1) DEFAULT \'1\' COMMENT \'aktivní\'');
        $this->addSql('ALTER TABLE tag CHANGE created_user_id created_user_id INT UNSIGNED DEFAULT NULL COMMENT \'id\', CHANGE changed_user_id changed_user_id INT UNSIGNED DEFAULT NULL COMMENT \'id\', CHANGE active active TINYINT(1) DEFAULT \'1\' NOT NULL COMMENT \'Platný\', CHANGE not_deleted not_deleted TINYINT(1) DEFAULT \'1\' COMMENT \'Nesmazaný\'');
        $this->addSql('ALTER TABLE user CHANGE created_user_id created_user_id INT UNSIGNED DEFAULT NULL COMMENT \'id\', CHANGE changed_user_id changed_user_id INT UNSIGNED DEFAULT NULL COMMENT \'id\', CHANGE active active TINYINT(1) DEFAULT \'1\' NOT NULL COMMENT \'Platný\', CHANGE not_deleted not_deleted TINYINT(1) DEFAULT \'1\' COMMENT \'Nesmazaný\'');
        $this->addSql('ALTER TABLE user_role CHANGE user_id user_id INT UNSIGNED DEFAULT NULL COMMENT \'id\', CHANGE role_id role_id INT UNSIGNED DEFAULT NULL COMMENT \'id\', CHANGE not_deleted not_deleted TINYINT(1) DEFAULT \'1\'');
    }

    public function down(Schema $schema) : void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('ALTER TABLE address CHANGE main main TINYINT(1) DEFAULT \'0\' NOT NULL');
        $this->addSql('ALTER TABLE article CHANGE changed_user_id changed_user_id INT UNSIGNED DEFAULT NULL COMMENT \'Kdo změnil\', CHANGE created_user_id created_user_id INT UNSIGNED NOT NULL COMMENT \'Id uživatele, který vytvořil článek\', CHANGE article_category_id article_category_id INT UNSIGNED DEFAULT 1 NOT NULL COMMENT \'Kategorie\', CHANGE active active TINYINT(1) DEFAULT \'1\' NOT NULL COMMENT \'Platný\', CHANGE not_deleted not_deleted TINYINT(1) DEFAULT \'1\' COMMENT \'Nesmazaný\'');
        $this->addSql('ALTER TABLE article_category CHANGE created_user_id created_user_id INT UNSIGNED NOT NULL COMMENT \'Vytvořil\', CHANGE changed_user_id changed_user_id INT UNSIGNED DEFAULT NULL COMMENT \'Kdo změnil\', CHANGE article_category_id article_category_id INT UNSIGNED DEFAULT 1 COMMENT \'Nadřazená kategorie\', CHANGE active active TINYINT(1) DEFAULT \'1\' NOT NULL COMMENT \'Platný\', CHANGE not_deleted not_deleted TINYINT(1) DEFAULT \'1\' COMMENT \'Nesmazaný\'');
        $this->addSql('ALTER TABLE article_tag DROP FOREIGN KEY FK_919694F97294869C');
        $this->addSql('ALTER TABLE article_tag DROP FOREIGN KEY FK_919694F9BAD26311');
        $this->addSql('ALTER TABLE article_tag CHANGE article_id article_id INT UNSIGNED NOT NULL COMMENT \'Vazba na article\', CHANGE tag_id tag_id INT UNSIGNED NOT NULL COMMENT \'Vazba na tag\', CHANGE not_deleted not_deleted TINYINT(1) DEFAULT \'1\' COMMENT \'Nesmazaný\'');
        $this->addSql('ALTER TABLE article_tag ADD CONSTRAINT article_tag_article_id FOREIGN KEY (article_id) REFERENCES article (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE article_tag ADD CONSTRAINT article_tag_tag_id FOREIGN KEY (tag_id) REFERENCES tag (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE author CHANGE changed_user_id changed_user_id INT UNSIGNED DEFAULT NULL COMMENT \'Změnil\', CHANGE created_user_id created_user_id INT UNSIGNED NOT NULL COMMENT \'Založil\', CHANGE image_file_id image_file_id INT UNSIGNED DEFAULT NULL COMMENT \'Obrázek\', CHANGE active active TINYINT(1) DEFAULT \'1\' NOT NULL COMMENT \'Platný\', CHANGE not_deleted not_deleted TINYINT(1) DEFAULT \'1\' COMMENT \'Nesmazaný\'');
        $this->addSql('ALTER TABLE author_in_product DROP FOREIGN KEY FK_DAF05BF8F675F31B');
        $this->addSql('ALTER TABLE author_in_product DROP FOREIGN KEY FK_DAF05BF84584665A');
        $this->addSql('ALTER TABLE author_in_product CHANGE author_id author_id INT UNSIGNED NOT NULL, CHANGE product_id product_id INT UNSIGNED NOT NULL, CHANGE not_deleted not_deleted TINYINT(1) DEFAULT \'1\'');
        $this->addSql('ALTER TABLE author_in_product ADD CONSTRAINT FK_author_in_product_author FOREIGN KEY (author_id) REFERENCES author (id) ON UPDATE CASCADE');
        $this->addSql('ALTER TABLE author_in_product ADD CONSTRAINT FK_author_in_product_product FOREIGN KEY (product_id) REFERENCES product (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE bank_code CHANGE created_user_id created_user_id INT UNSIGNED DEFAULT NULL COMMENT \'Vytvořil\', CHANGE changed_user_id changed_user_id INT UNSIGNED DEFAULT NULL COMMENT \'Změnil\', CHANGE active active TINYINT(1) DEFAULT \'1\' NOT NULL COMMENT \'Aktivní\', CHANGE not_deleted not_deleted TINYINT(1) DEFAULT \'1\' COMMENT \'Nesmazaný\'');
        $this->addSql('ALTER TABLE customer CHANGE state_id state_id SMALLINT UNSIGNED DEFAULT 39 NOT NULL COMMENT \'stát\', CHANGE created_user_id created_user_id INT UNSIGNED NOT NULL COMMENT \'kdo vytvořil\', CHANGE changed_user_id changed_user_id INT UNSIGNED DEFAULT NULL COMMENT \'Kdo změnil\', CHANGE active active TINYINT(1) DEFAULT \'1\' NOT NULL COMMENT \'Platný\', CHANGE not_deleted not_deleted TINYINT(1) DEFAULT \'1\' COMMENT \'Nesmazaný\'');
        $this->addSql('ALTER TABLE customer2 CHANGE state_id state_id SMALLINT UNSIGNED DEFAULT 39 NOT NULL COMMENT \'stát\', CHANGE active active TINYINT(1) DEFAULT \'1\' NOT NULL COMMENT \'Platný\', CHANGE not_deleted not_deleted TINYINT(1) DEFAULT \'1\' COMMENT \'Nesmazaný\'');
        $this->addSql('ALTER TABLE file CHANGE image image TINYINT(1) DEFAULT \'0\' NOT NULL COMMENT \'Obrázek?\', CHANGE active active TINYINT(1) DEFAULT \'1\' NOT NULL COMMENT \'Platný\', CHANGE not_deleted not_deleted TINYINT(1) DEFAULT \'1\' COMMENT \'Nesmazaný\'');
        $this->addSql('ALTER TABLE help CHANGE not_deleted not_deleted TINYINT(1) DEFAULT \'1\' COMMENT \'Aktivní\'');
        $this->addSql('ALTER TABLE history CHANGE created_user_id created_user_id INT UNSIGNED DEFAULT NULL COMMENT \'id uživatele, který provedl změnu\', CHANGE not_deleted not_deleted TINYINT(1) DEFAULT \'1\' COMMENT \'Nesmazaný\'');
        $this->addSql('ALTER TABLE history_data DROP FOREIGN KEY FK_A6C6831F1E058452');
        $this->addSql('ALTER TABLE history_data CHANGE history_id history_id BIGINT UNSIGNED NOT NULL COMMENT \'id historie\'');
        $this->addSql('ALTER TABLE history_data ADD CONSTRAINT history_data_ibfk_1 FOREIGN KEY (history_id) REFERENCES history (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE invoice CHANGE customer_id customer_id INT UNSIGNED NOT NULL COMMENT \'Zákazník\', CHANGE paid paid TINYINT(1) DEFAULT \'0\' NOT NULL COMMENT \'Zaplaceno\', CHANGE active active TINYINT(1) DEFAULT \'1\' NOT NULL COMMENT \'Platný\', CHANGE not_deleted not_deleted TINYINT(1) DEFAULT \'1\' COMMENT \'Nesmazaný\'');
        $this->addSql('ALTER TABLE invoice_delivery CHANGE invoice_id invoice_id INT UNSIGNED NOT NULL COMMENT \'Faktura\', CHANGE active active TINYINT(1) DEFAULT \'1\' NOT NULL COMMENT \'Platný\', CHANGE not_deleted not_deleted TINYINT(1) DEFAULT \'1\' COMMENT \'Nesmazaný\'');
        $this->addSql('ALTER TABLE invoice_product CHANGE invoice_id invoice_id INT UNSIGNED NOT NULL COMMENT \'Faktura\', CHANGE created_user_id created_user_id INT UNSIGNED NOT NULL COMMENT \'Vytvořil\', CHANGE product_id product_id INT UNSIGNED NOT NULL COMMENT \'Produkt\', CHANGE active active TINYINT(1) DEFAULT \'1\' NOT NULL COMMENT \'Platný\', CHANGE not_deleted not_deleted TINYINT(1) DEFAULT \'1\' NOT NULL COMMENT \'Nesmazaný\'');
        $this->addSql('ALTER TABLE language CHANGE id id TINYINT(1) NOT NULL COMMENT \'Id\', CHANGE active active TINYINT(1) DEFAULT \'1\' NOT NULL COMMENT \'Platný\', CHANGE not_deleted not_deleted TINYINT(1) DEFAULT \'1\' COMMENT \'Nesmazaný\'');
        $this->addSql('ALTER TABLE login_log CHANGE user_id user_id INT UNSIGNED DEFAULT NULL, CHANGE not_deleted not_deleted TINYINT(1) DEFAULT \'1\'');
        $this->addSql('ALTER TABLE message CHANGE sender_user_id sender_user_id INT UNSIGNED NOT NULL COMMENT \'odesílatel\', CHANGE recipient_user_id recipient_user_id INT UNSIGNED NOT NULL COMMENT \'příjemce\', CHANGE `read` `read` TINYINT(1) DEFAULT \'0\' NOT NULL COMMENT \'přečteno příjemcem\', CHANGE active active TINYINT(1) DEFAULT \'1\' NOT NULL COMMENT \'Aktivní\', CHANGE not_deleted not_deleted TINYINT(1) DEFAULT \'1\' COMMENT \'Nesmazaný\'');
        $this->addSql('ALTER TABLE notification CHANGE `read` `read` TINYINT(1) DEFAULT \'0\' NOT NULL COMMENT \'přečteno příjemcem\', CHANGE active active TINYINT(1) DEFAULT \'1\' NOT NULL COMMENT \'Aktivní\', CHANGE not_deleted not_deleted TINYINT(1) DEFAULT \'1\' COMMENT \'Nesmazaný\'');
        $this->addSql('ALTER TABLE `order` CHANGE user_id user_id INT UNSIGNED NOT NULL, CHANGE shipping_id shipping_id INT UNSIGNED NOT NULL, CHANGE payment_id payment_id INT UNSIGNED NOT NULL, CHANGE shipping_address_id shipping_address_id INT UNSIGNED NOT NULL, CHANGE invoice_address_id invoice_address_id INT UNSIGNED NOT NULL, CHANGE created_user_id created_user_id INT UNSIGNED NOT NULL, CHANGE changed_user_id changed_user_id INT UNSIGNED NOT NULL');
        $this->addSql('ALTER TABLE payment CHANGE online_payment online_payment TINYINT(1) DEFAULT \'0\' COMMENT \'Online platba\'');
        $this->addSql('ALTER TABLE product CHANGE created_user_id created_user_id INT UNSIGNED NOT NULL COMMENT \'Vytvořil\', CHANGE changed_user_id changed_user_id INT UNSIGNED DEFAULT NULL COMMENT \'Změnil\', CHANGE language_id language_id TINYINT(1) DEFAULT NULL COMMENT \'Jazyk\', CHANGE product_availability_id product_availability_id SMALLINT UNSIGNED DEFAULT NULL COMMENT \'Dostupnost\', CHANGE product_category_id product_category_id INT UNSIGNED DEFAULT 1 NOT NULL COMMENT \'Kategorie\', CHANGE vat vat NUMERIC(4, 2) UNSIGNED DEFAULT NULL COMMENT \'DPH\', CHANGE news news TINYINT(1) DEFAULT \'0\' NOT NULL COMMENT \'Novinka\', CHANGE active active TINYINT(1) DEFAULT \'1\' NOT NULL COMMENT \'Platný\', CHANGE not_deleted not_deleted TINYINT(1) DEFAULT \'1\' COMMENT \'Nesmazaný\'');
        $this->addSql('ALTER TABLE product_category CHANGE created_user_id created_user_id INT UNSIGNED NOT NULL COMMENT \'Vytvořil\', CHANGE changed_user_id changed_user_id INT UNSIGNED DEFAULT NULL COMMENT \'Kdo změnil\', CHANGE product_category_id product_category_id INT UNSIGNED DEFAULT 1 COMMENT \'Nadřazená kategorie\', CHANGE active active TINYINT(1) DEFAULT \'1\' NOT NULL COMMENT \'Platný\', CHANGE not_deleted not_deleted TINYINT(1) DEFAULT \'1\' COMMENT \'Nesmazaný\'');
        $this->addSql('ALTER TABLE product_image CHANGE product_id product_id INT UNSIGNED DEFAULT NULL COMMENT \'Produkt\', CHANGE created_user_id created_user_id INT UNSIGNED NOT NULL COMMENT \'Vytvořil\', CHANGE changed_user_id changed_user_id INT UNSIGNED DEFAULT NULL COMMENT \'Změnil\', CHANGE file_id file_id INT UNSIGNED NOT NULL COMMENT \'Soubor obrázku\', CHANGE main main TINYINT(1) DEFAULT \'0\' NOT NULL COMMENT \'Hlavní\', CHANGE active active TINYINT(1) DEFAULT \'1\' NOT NULL COMMENT \'Platný\', CHANGE not_deleted not_deleted TINYINT(1) DEFAULT \'1\' COMMENT \'Nesmazaný\'');
        $this->addSql('ALTER TABLE redirect CHANGE hits hits INT UNSIGNED DEFAULT 0 NOT NULL COMMENT \'Počet použití\', CHANGE extra extra TINYINT(1) DEFAULT \'0\' NOT NULL COMMENT \'Extra sitemap\'');
        $this->addSql('ALTER TABLE role CHANGE created_user_id created_user_id INT UNSIGNED NOT NULL COMMENT \'Vytvořil\', CHANGE changed_user_id changed_user_id INT UNSIGNED DEFAULT NULL COMMENT \'Kdo změnil\', CHANGE active active TINYINT(1) DEFAULT \'1\' NOT NULL COMMENT \'Platný\', CHANGE not_deleted not_deleted TINYINT(1) DEFAULT \'1\' COMMENT \'Nesmazaný\'');
        $this->addSql('ALTER TABLE rtgrid_state CHANGE id id VARCHAR(40) CHARACTER SET utf8 DEFAULT \'\' NOT NULL COLLATE `utf8_czech_ci`, CHANGE user_id user_id INT UNSIGNED DEFAULT 0 NOT NULL');
        $this->addSql('ALTER TABLE settings CHANGE not_deleted not_deleted TINYINT(1) DEFAULT \'1\'');
        $this->addSql('ALTER TABLE state CHANGE not_deleted not_deleted TINYINT(1) DEFAULT \'1\' COMMENT \'aktivní\'');
        $this->addSql('ALTER TABLE tag CHANGE created_user_id created_user_id INT UNSIGNED DEFAULT NULL COMMENT \'Vytvořil\', CHANGE changed_user_id changed_user_id INT UNSIGNED DEFAULT NULL COMMENT \'Kdo změnil\', CHANGE active active TINYINT(1) DEFAULT \'1\' NOT NULL COMMENT \'Platný\', CHANGE not_deleted not_deleted TINYINT(1) DEFAULT \'1\' COMMENT \'Nesmazaný\'');
        $this->addSql('ALTER TABLE user CHANGE created_user_id created_user_id INT UNSIGNED DEFAULT NULL COMMENT \'Vytvořil\', CHANGE changed_user_id changed_user_id INT UNSIGNED DEFAULT NULL COMMENT \'Kdo změnil\', CHANGE active active TINYINT(1) DEFAULT \'1\' NOT NULL COMMENT \'Platný\', CHANGE not_deleted not_deleted TINYINT(1) DEFAULT \'1\' COMMENT \'Nesmazaný\'');
        $this->addSql('ALTER TABLE user_role CHANGE role_id role_id INT UNSIGNED NOT NULL, CHANGE user_id user_id INT UNSIGNED NOT NULL, CHANGE not_deleted not_deleted TINYINT(1) DEFAULT \'1\'');
    }
}
