<?php

declare(strict_types=1);

namespace DB\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20211015125404 extends AbstractMigration
{
    public function getDescription() : string
    {
        return '';
    }

    public function up(Schema $schema) : void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('ALTER TABLE author_in_product DROP FOREIGN KEY FK_author_in_product_author');
        $this->addSql('ALTER TABLE invoice DROP FOREIGN KEY invoice_customer_ibfk_1');
        $this->addSql('ALTER TABLE author DROP FOREIGN KEY author_ibfk_3');
        $this->addSql('ALTER TABLE product_image DROP FOREIGN KEY product_image_ibfk_4');
        $this->addSql('ALTER TABLE history_data DROP FOREIGN KEY history_data_ibfk_1');
        $this->addSql('ALTER TABLE invoice_delivery DROP FOREIGN KEY invoice_delivery_ibfk_1');
        $this->addSql('ALTER TABLE invoice_product DROP FOREIGN KEY invoice_product_ibfk_1');
        $this->addSql('ALTER TABLE product DROP FOREIGN KEY product_ibfk_3');
        $this->addSql('ALTER TABLE author_in_product DROP FOREIGN KEY FK_author_in_product_product');
        $this->addSql('ALTER TABLE invoice_product DROP FOREIGN KEY invoice_product_ibfk_3');
        $this->addSql('ALTER TABLE product_image DROP FOREIGN KEY product_image_ibfk_1');
        $this->addSql('ALTER TABLE product DROP FOREIGN KEY product_ibfk_4');
        $this->addSql('ALTER TABLE product DROP FOREIGN KEY product_ibfk_5');
        $this->addSql('ALTER TABLE product_category DROP FOREIGN KEY product_category_ibfk_3');
        $this->addSql('ALTER TABLE user_role DROP FOREIGN KEY fk_user_role_role1');
        $this->addSql('ALTER TABLE customer DROP FOREIGN KEY customer_ibfk_1');
        $this->addSql('ALTER TABLE customer2 DROP FOREIGN KEY customer2_ibfk_1');
        $this->addSql('ALTER TABLE article DROP FOREIGN KEY article_ibfk_1');
        $this->addSql('ALTER TABLE article DROP FOREIGN KEY article_ibfk_2');
        $this->addSql('ALTER TABLE article_category DROP FOREIGN KEY article_category_ibfk_1');
        $this->addSql('ALTER TABLE article_category DROP FOREIGN KEY article_category_ibfk_2');
        $this->addSql('ALTER TABLE author DROP FOREIGN KEY author_ibfk_1');
        $this->addSql('ALTER TABLE author DROP FOREIGN KEY author_ibfk_2');
        $this->addSql('ALTER TABLE bank_code DROP FOREIGN KEY bank_code_ibfk_1');
        $this->addSql('ALTER TABLE bank_code DROP FOREIGN KEY bank_code_ibfk_2');
        $this->addSql('ALTER TABLE customer DROP FOREIGN KEY customer_ibfk_2');
        $this->addSql('ALTER TABLE customer DROP FOREIGN KEY customer_ibfk_3');
        $this->addSql('ALTER TABLE history DROP FOREIGN KEY history_ibfk_1');
        $this->addSql('ALTER TABLE invoice_product DROP FOREIGN KEY invoice_product_ibfk_2');
        $this->addSql('ALTER TABLE login_log DROP FOREIGN KEY login_log_ibfk_1');
        $this->addSql('ALTER TABLE message DROP FOREIGN KEY message_ibfk_1');
        $this->addSql('ALTER TABLE message DROP FOREIGN KEY message_ibfk_2');
        $this->addSql('ALTER TABLE product DROP FOREIGN KEY product_ibfk_1');
        $this->addSql('ALTER TABLE product DROP FOREIGN KEY product_ibfk_2');
        $this->addSql('ALTER TABLE product_category DROP FOREIGN KEY product_category_ibfk_1');
        $this->addSql('ALTER TABLE product_category DROP FOREIGN KEY product_category_ibfk_2');
        $this->addSql('ALTER TABLE product_image DROP FOREIGN KEY product_image_ibfk_2');
        $this->addSql('ALTER TABLE product_image DROP FOREIGN KEY product_image_ibfk_3');
        $this->addSql('ALTER TABLE role DROP FOREIGN KEY role_ibfk_1');
        $this->addSql('ALTER TABLE role DROP FOREIGN KEY role_ibfk_2');
        $this->addSql('ALTER TABLE tag DROP FOREIGN KEY tag_ibfk_1');
        $this->addSql('ALTER TABLE tag DROP FOREIGN KEY tag_ibfk_2');
        $this->addSql('ALTER TABLE user DROP FOREIGN KEY user_ibfk_1');
        $this->addSql('ALTER TABLE user DROP FOREIGN KEY user_ibfk_2');
        $this->addSql('ALTER TABLE user_role DROP FOREIGN KEY fk_user_role_user1');
        $this->addSql('CREATE TABLE book (id INT AUTO_INCREMENT NOT NULL, category_id INT NOT NULL, title VARCHAR(255) NOT NULL, already_read TINYINT(1) NOT NULL, created_at VARCHAR(255) NOT NULL, updated_at VARCHAR(255) DEFAULT NULL, INDEX IDX_CBE5A33112469DE2 (category_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE category (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ext_log_entries (id INT AUTO_INCREMENT NOT NULL, action VARCHAR(8) NOT NULL, logged_at DATETIME NOT NULL, object_id VARCHAR(64) DEFAULT NULL, object_class VARCHAR(191) NOT NULL, version INT NOT NULL, data LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:array)\', username VARCHAR(191) DEFAULT NULL, INDEX log_class_lookup_idx (object_class), INDEX log_date_lookup_idx (logged_at), INDEX log_user_lookup_idx (username), INDEX log_version_lookup_idx (object_id, object_class, version), PRIMARY KEY(id)) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB ROW_FORMAT = DYNAMIC');
        $this->addSql('CREATE TABLE ext_translations (id INT AUTO_INCREMENT NOT NULL, locale VARCHAR(8) NOT NULL, object_class VARCHAR(191) NOT NULL, field VARCHAR(32) NOT NULL, foreign_key VARCHAR(64) NOT NULL, content LONGTEXT DEFAULT NULL, INDEX translations_lookup_idx (locale, object_class, foreign_key), UNIQUE INDEX lookup_unique_idx (locale, object_class, field, foreign_key), PRIMARY KEY(id)) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB ROW_FORMAT = DYNAMIC');
        $this->addSql('CREATE TABLE tag_book (tag_id INT NOT NULL, book_id INT NOT NULL, INDEX IDX_25EA1C87BAD26311 (tag_id), INDEX IDX_25EA1C8716A2B381 (book_id), PRIMARY KEY(tag_id, book_id)) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('ALTER TABLE book ADD CONSTRAINT FK_CBE5A33112469DE2 FOREIGN KEY (category_id) REFERENCES category (id)');
        $this->addSql('ALTER TABLE tag_book ADD CONSTRAINT FK_25EA1C87BAD26311 FOREIGN KEY (tag_id) REFERENCES tag (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE tag_book ADD CONSTRAINT FK_25EA1C8716A2B381 FOREIGN KEY (book_id) REFERENCES book (id) ON DELETE CASCADE');
        $this->addSql('DROP TABLE article_tag');
        $this->addSql('DROP TABLE author');
        $this->addSql('DROP TABLE author_in_product');
        $this->addSql('DROP TABLE bank_code');
        $this->addSql('DROP TABLE customer');
        $this->addSql('DROP TABLE customer2');
        $this->addSql('DROP TABLE file');
        $this->addSql('DROP TABLE help');
        $this->addSql('DROP TABLE history');
        $this->addSql('DROP TABLE history_data');
        $this->addSql('DROP TABLE holiday');
        $this->addSql('DROP TABLE invoice');
        $this->addSql('DROP TABLE invoice_delivery');
        $this->addSql('DROP TABLE invoice_product');
        $this->addSql('DROP TABLE language');
        $this->addSql('DROP TABLE login_log');
        $this->addSql('DROP TABLE message');
        $this->addSql('DROP TABLE notification');
        $this->addSql('DROP TABLE payment');
        $this->addSql('DROP TABLE product');
        $this->addSql('DROP TABLE product_availability');
        $this->addSql('DROP TABLE product_category');
        $this->addSql('DROP TABLE product_image');
        $this->addSql('DROP TABLE redirect');
        $this->addSql('DROP TABLE role');
        $this->addSql('DROP TABLE rtgrid_state');
        $this->addSql('DROP TABLE settings');
        $this->addSql('DROP TABLE shipping');
        $this->addSql('DROP TABLE state');
        $this->addSql('DROP TABLE user');
        $this->addSql('DROP TABLE user_role');
        $this->addSql('ALTER TABLE article DROP FOREIGN KEY article_ibfk_3');
        $this->addSql('DROP INDEX changed_user_id ON article');
        $this->addSql('DROP INDEX article_category_id ON article');
        $this->addSql('DROP INDEX created_user_id ON article');
        $this->addSql('ALTER TABLE article ADD category_id INT DEFAULT NULL, ADD content LONGTEXT NOT NULL, ADD updated DATETIME NOT NULL, ADD content_changed DATETIME DEFAULT NULL, ADD deletedAt DATETIME DEFAULT NULL, DROP article_category_id, DROP created_user_id, DROP changed_user_id, DROP intro, DROP text, DROP valid_from, DROP valid_to, DROP changed, DROP active, DROP not_deleted, CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE slug slug VARCHAR(128) NOT NULL, CHANGE title title VARCHAR(128) NOT NULL, CHANGE created created DATETIME NOT NULL');
        $this->addSql('ALTER TABLE article ADD CONSTRAINT FK_23A0E6612469DE2 FOREIGN KEY (category_id) REFERENCES article_category (id) ON DELETE CASCADE');
        $this->addSql('CREATE INDEX IDX_23A0E6612469DE2 ON article (category_id)');
        $this->addSql('ALTER TABLE article RENAME INDEX slug TO UNIQ_23A0E66989D9B62');
        $this->addSql('ALTER TABLE article_category DROP FOREIGN KEY article_category_ibfk_3');
        $this->addSql('DROP INDEX created_user_id ON article_category');
        $this->addSql('DROP INDEX article_category_id ON article_category');
        $this->addSql('DROP INDEX name_unique ON article_category');
        $this->addSql('DROP INDEX slug ON article_category');
        $this->addSql('DROP INDEX changed_user_id ON article_category');
        $this->addSql('ALTER TABLE article_category ADD tree_root INT DEFAULT NULL, ADD parent_id INT DEFAULT NULL, ADD title VARCHAR(64) NOT NULL, ADD lft INT NOT NULL, ADD lvl INT NOT NULL, ADD rgt INT NOT NULL, DROP article_category_id, DROP created_user_id, DROP changed_user_id, DROP slug, DROP name, DROP created, DROP changed, DROP active, DROP not_deleted, CHANGE id id INT AUTO_INCREMENT NOT NULL');
        $this->addSql('ALTER TABLE article_category ADD CONSTRAINT FK_53A4EDAAA977936C FOREIGN KEY (tree_root) REFERENCES article_category (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE article_category ADD CONSTRAINT FK_53A4EDAA727ACA70 FOREIGN KEY (parent_id) REFERENCES article_category (id) ON DELETE CASCADE');
        $this->addSql('CREATE INDEX IDX_53A4EDAAA977936C ON article_category (tree_root)');
        $this->addSql('CREATE INDEX IDX_53A4EDAA727ACA70 ON article_category (parent_id)');
        $this->addSql('DROP INDEX changed_user_id ON tag');
        $this->addSql('DROP INDEX created_user_id ON tag');
        $this->addSql('ALTER TABLE tag ADD title VARCHAR(255) NOT NULL, DROP created_user_id, DROP changed_user_id, DROP name, DROP created, DROP changed, DROP active, DROP not_deleted, CHANGE id id INT AUTO_INCREMENT NOT NULL');
    }

    public function down(Schema $schema) : void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('ALTER TABLE tag_book DROP FOREIGN KEY FK_25EA1C8716A2B381');
        $this->addSql('ALTER TABLE book DROP FOREIGN KEY FK_CBE5A33112469DE2');
        $this->addSql('CREATE TABLE article_tag (id INT UNSIGNED AUTO_INCREMENT NOT NULL COMMENT \'Primární klíč\', article_id INT UNSIGNED NOT NULL COMMENT \'Vazba na article\', tag_id INT UNSIGNED NOT NULL COMMENT \'Vazba na tag\', not_deleted TINYINT(1) DEFAULT \'1\' COMMENT \'Nesmazaný\', INDEX article_tag_article_id (article_id), INDEX article_tag_tag_id (tag_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'Propojovací tabulka mezi článkem a štítkem\' ');
        $this->addSql('CREATE TABLE author (id INT UNSIGNED AUTO_INCREMENT NOT NULL COMMENT \'Id\', image_file_id INT UNSIGNED DEFAULT NULL COMMENT \'Obrázek\', created_user_id INT UNSIGNED NOT NULL COMMENT \'Založil\', changed_user_id INT UNSIGNED DEFAULT NULL COMMENT \'Změnil\', slug VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci` COMMENT \'Identifikátor\', lastname VARCHAR(100) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci` COMMENT \'Příjmení\', firstname VARCHAR(100) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci` COMMENT \'Jméno\', `desc` TEXT CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci` COMMENT \'Popis\', created DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT \'Vytvořeno\', changed DATETIME DEFAULT NULL COMMENT \'Změněno\', active TINYINT(1) DEFAULT \'1\' NOT NULL COMMENT \'Platný\', not_deleted TINYINT(1) DEFAULT \'1\' COMMENT \'Nesmazaný\', INDEX changed_user_id (changed_user_id), INDEX image_file_id (image_file_id), UNIQUE INDEX slug (slug), INDEX created_user_id (created_user_id), FULLTEXT INDEX lastname_firstname (lastname, firstname), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE author_in_product (id INT UNSIGNED AUTO_INCREMENT NOT NULL, author_id INT UNSIGNED NOT NULL, product_id INT UNSIGNED NOT NULL, created DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, not_deleted TINYINT(1) DEFAULT \'1\', INDEX not_deleted (not_deleted), INDEX FK_author_in_product_product (product_id), UNIQUE INDEX author_id_product_id_not_deleted (author_id, product_id, not_deleted), INDEX author_id (author_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE bank_code (id INT UNSIGNED AUTO_INCREMENT NOT NULL COMMENT \'Primární klíč\', created_user_id INT UNSIGNED DEFAULT NULL COMMENT \'Vytvořil\', changed_user_id INT UNSIGNED DEFAULT NULL COMMENT \'Změnil\', bank_code VARCHAR(4) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci` COMMENT \'Kód banky\', created DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT \'Vytvořeno\', changed DATETIME DEFAULT NULL COMMENT \'Změněno\', active TINYINT(1) DEFAULT \'1\' NOT NULL COMMENT \'Aktivní\', not_deleted TINYINT(1) DEFAULT \'1\' COMMENT \'Nesmazaný\', INDEX changed_user_id (changed_user_id), INDEX created_user_id (created_user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE customer (id INT UNSIGNED AUTO_INCREMENT NOT NULL COMMENT \'id\', state_id SMALLINT UNSIGNED DEFAULT 39 NOT NULL COMMENT \'stát\', created_user_id INT UNSIGNED NOT NULL COMMENT \'kdo vytvořil\', changed_user_id INT UNSIGNED DEFAULT NULL COMMENT \'Kdo změnil\', ico VARCHAR(30) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci` COMMENT \'ičo\', dic VARCHAR(30) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci` COMMENT \'dič\', firstname VARCHAR(100) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci` COMMENT \'jméno\', lastname VARCHAR(100) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci` COMMENT \'příjmení\', street VARCHAR(100) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci` COMMENT \'ulice\', land_registry_number VARCHAR(100) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci` COMMENT \'popisné číslo\', house_number VARCHAR(100) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci` COMMENT \'orientační číslo\', city VARCHAR(100) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci` COMMENT \'město\', postcode VARCHAR(100) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci` COMMENT \'PSČ/zip\', phone_pre VARCHAR(10) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci` COMMENT \'telefon - předvolba\', phone VARCHAR(100) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci` COMMENT \'telefon\', email VARCHAR(100) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci` COMMENT \'email\', person_type VARCHAR(255) CHARACTER SET utf8 DEFAULT \'natural\' NOT NULL COLLATE `utf8_general_ci` COMMENT \'druh osoby\', account_prefix VARCHAR(6) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci` COMMENT \'předčíslí účtu\', account_number VARCHAR(10) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci` COMMENT \'číslo účtu\', account_bank VARCHAR(4) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci` COMMENT \'číslo banky\', value NUMERIC(12, 2) DEFAULT NULL COMMENT \'hodnota\', note TEXT CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci` COMMENT \'poznámka\', created DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT \'datum vytvoření\', changed DATETIME DEFAULT NULL COMMENT \'Čas úpravy\', active TINYINT(1) DEFAULT \'1\' NOT NULL COMMENT \'Platný\', not_deleted TINYINT(1) DEFAULT \'1\' COMMENT \'Nesmazaný\', INDEX state_id (state_id), UNIQUE INDEX email_unique (email, not_deleted), INDEX user_created_id (created_user_id), INDEX changed_user_id (changed_user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE customer2 (id INT UNSIGNED AUTO_INCREMENT NOT NULL COMMENT \'id\', state_id SMALLINT UNSIGNED DEFAULT 39 NOT NULL COMMENT \'stát\', firstname VARCHAR(100) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci` COMMENT \'jméno\', lastname VARCHAR(100) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci` COMMENT \'příjmení\', street VARCHAR(100) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci` COMMENT \'ulice\', land_registry_number VARCHAR(100) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci` COMMENT \'popisné číslo\', house_number VARCHAR(100) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci` COMMENT \'orientační číslo\', city VARCHAR(100) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci` COMMENT \'město\', postcode VARCHAR(100) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci` COMMENT \'PSČ/zip\', phone_pre VARCHAR(10) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci` COMMENT \'telefon - předvolba\', phone VARCHAR(100) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci` COMMENT \'telefon\', email VARCHAR(100) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci` COMMENT \'email\', person_type VARCHAR(255) CHARACTER SET utf8 DEFAULT \'natural\' NOT NULL COLLATE `utf8_general_ci` COMMENT \'druh osoby\', account_prefix VARCHAR(6) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci` COMMENT \'předčíslí účtu\', account_number VARCHAR(10) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci` COMMENT \'číslo účtu\', account_bank VARCHAR(4) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci` COMMENT \'číslo banky\', value NUMERIC(12, 2) DEFAULT NULL COMMENT \'hodnota\', note TEXT CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci` COMMENT \'poznámka\', created DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT \'datum vytvoření\', created_user_id INT UNSIGNED NOT NULL COMMENT \'kdo vytvořil\', changed DATETIME DEFAULT NULL COMMENT \'Čas úpravy\', changed_user_id INT UNSIGNED DEFAULT NULL COMMENT \'Kdo změnil\', active TINYINT(1) DEFAULT \'1\' NOT NULL COMMENT \'Platný\', not_deleted TINYINT(1) DEFAULT \'1\' COMMENT \'Nesmazaný\', INDEX state_id (state_id), UNIQUE INDEX email_unique (email, not_deleted), INDEX user_created_id (created_user_id), INDEX changed_user_id (changed_user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE file (id INT UNSIGNED AUTO_INCREMENT NOT NULL COMMENT \'Id\', filepath VARCHAR(100) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci` COMMENT \'Relativní cesta a název souboru, kde je soubor uložen v adresáři www/files\', ext VARCHAR(10) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci` COMMENT \'Přípona souboru obrázku (dle toho se i určí typ)\', mime_type VARCHAR(100) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci` COMMENT \'Mime typ\', image TINYINT(1) DEFAULT \'0\' NOT NULL COMMENT \'Obrázek?\', original_filename VARCHAR(1000) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci` COMMENT \'Původní název souboru\', created DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT \'Vytvořeno\', created_user_id INT UNSIGNED NOT NULL COMMENT \'Vytvořil\', changed DATETIME DEFAULT NULL COMMENT \'Změněno\', changed_user_id INT UNSIGNED DEFAULT NULL COMMENT \'Změnil\', active TINYINT(1) DEFAULT \'1\' NOT NULL COMMENT \'Platný\', not_deleted TINYINT(1) DEFAULT \'1\' COMMENT \'Nesmazaný\', INDEX changed_user_id (changed_user_id), INDEX user_id (created_user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE help (id INT UNSIGNED AUTO_INCREMENT NOT NULL COMMENT \'Primární klíč\', presenter VARCHAR(32) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci` COMMENT \'Jméno presenteru\', action VARCHAR(32) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci` COMMENT \'Jméno akce\', text TEXT CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci` COMMENT \'Vlastní text popisu\', not_deleted TINYINT(1) DEFAULT \'1\' COMMENT \'Aktivní\', PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'Tabulka slouží k vypsání informací v tooltip pro konkrétní presenter a akci\' ');
        $this->addSql('CREATE TABLE history (id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL COMMENT \'id\', created_user_id INT UNSIGNED DEFAULT NULL COMMENT \'id uživatele, který provedl změnu\', table_name VARCHAR(100) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci` COMMENT \'název tabulky\', table_id INT UNSIGNED NOT NULL COMMENT \'id záznamu v tabulce\', changed DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT \'datum a čas změny záznamu\', not_deleted TINYINT(1) DEFAULT \'1\' COMMENT \'Nesmazaný\', INDEX table_name_id (table_name, table_id), INDEX user_id (created_user_id), INDEX table_name (table_name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'Historie\' ');
        $this->addSql('CREATE TABLE history_data (id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL COMMENT \'id\', history_id BIGINT UNSIGNED NOT NULL COMMENT \'id historie\', `column` VARCHAR(100) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci` COMMENT \'název sloupce\', old_value TEXT CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci` COMMENT \'stará hodnota\', new_value TEXT CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci` COMMENT \'nová hodnota\', `ignore` TINYINT(1) DEFAULT NULL, not_deleted TINYINT(1) DEFAULT \'1\' NOT NULL COMMENT \'Nesmazaný\', INDEX history_id (history_id), UNIQUE INDEX `ignore` (`ignore`), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'Historie - data\' ');
        $this->addSql('CREATE TABLE holiday (id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, holiday_date DATE NOT NULL, name VARCHAR(49) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, UNIQUE INDEX holiday_date (holiday_date), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE invoice (id INT UNSIGNED AUTO_INCREMENT NOT NULL COMMENT \'Id\', customer_id INT UNSIGNED NOT NULL COMMENT \'Zákazník\', name VARCHAR(255) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci` COMMENT \'Název\', paid TINYINT(1) DEFAULT \'0\' NOT NULL COMMENT \'Zaplaceno\', created DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT \'Záznam vytvořen\', created_user_id INT UNSIGNED DEFAULT NULL COMMENT \'Vytvořil\', changed DATETIME DEFAULT NULL COMMENT \'Změněno\', changed_user_id INT UNSIGNED DEFAULT NULL COMMENT \'Změnil\', due_date DATETIME NOT NULL COMMENT \'Datum splatnosti\', active TINYINT(1) DEFAULT \'1\' NOT NULL COMMENT \'Platný\', not_deleted TINYINT(1) DEFAULT \'1\' COMMENT \'Nesmazaný\', INDEX invoice_customer_ibfk_1 (customer_id), INDEX created_user_id (created_user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE invoice_delivery (id INT UNSIGNED AUTO_INCREMENT NOT NULL COMMENT \'Id\', invoice_id INT UNSIGNED NOT NULL COMMENT \'Faktura\', customer_id INT UNSIGNED NOT NULL COMMENT \'Zákazník\', firstname VARCHAR(100) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci` COMMENT \'jméno\', lastname VARCHAR(100) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci` COMMENT \'příjmení\', street VARCHAR(100) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci` COMMENT \'ulice\', land_registry_number VARCHAR(100) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci` COMMENT \'popisné číslo\', house_number VARCHAR(100) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci` COMMENT \'orientační číslo\', city VARCHAR(100) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci` COMMENT \'město\', postcode VARCHAR(100) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci` COMMENT \'PSČ/zip\', state_id SMALLINT DEFAULT NULL COMMENT \'stát\', phone_pre VARCHAR(10) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci` COMMENT \'telefon - předvolba\', phone VARCHAR(100) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci` COMMENT \'telefon\', email VARCHAR(100) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci` COMMENT \'email\', created DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT \'datum vytvoření\', created_user_id INT UNSIGNED NOT NULL COMMENT \'kdo vytvořil\', changed DATETIME DEFAULT NULL COMMENT \'Čas úpravy\', changed_user_id INT UNSIGNED DEFAULT NULL COMMENT \'Kdo změnil\', active TINYINT(1) DEFAULT \'1\' NOT NULL COMMENT \'Platný\', not_deleted TINYINT(1) DEFAULT \'1\' COMMENT \'Nesmazaný\', INDEX invoice_id (invoice_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE invoice_product (id INT UNSIGNED AUTO_INCREMENT NOT NULL COMMENT \'Id\', invoice_id INT UNSIGNED NOT NULL COMMENT \'Faktura\', product_id INT UNSIGNED NOT NULL COMMENT \'Produkt\', created_user_id INT UNSIGNED NOT NULL COMMENT \'Vytvořil\', count INT UNSIGNED NOT NULL COMMENT \'Počet\', name VARCHAR(400) CHARACTER SET utf8 NOT NULL COLLATE `utf8_czech_ci` COMMENT \'Název\', price NUMERIC(14, 2) DEFAULT NULL COMMENT \'Cena\', vat NUMERIC(4, 2) DEFAULT NULL COMMENT \'DPH\', price_with_vat NUMERIC(14, 2) DEFAULT NULL COMMENT \'Cena s DPH\', created DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT \'Vytvořeno\', changed DATETIME DEFAULT NULL COMMENT \'Změněno\', changed_user_id INT UNSIGNED DEFAULT NULL COMMENT \'Změnil\', active TINYINT(1) DEFAULT \'1\' NOT NULL COMMENT \'Platný\', not_deleted TINYINT(1) DEFAULT \'1\' NOT NULL COMMENT \'Nesmazaný\', INDEX invoice_product_ibfk_1 (invoice_id), INDEX invoice_product_ibfk_3 (product_id), INDEX invoice_id (id), INDEX invoice_product_ibfk_2 (created_user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE language (id TINYINT(1) NOT NULL COMMENT \'Id\', name VARCHAR(200) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci` COMMENT \'Název\', fullname VARCHAR(200) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci` COMMENT \'Celý název\', active TINYINT(1) DEFAULT \'1\' NOT NULL COMMENT \'Platný\', not_deleted TINYINT(1) DEFAULT \'1\' COMMENT \'Nesmazaný\', UNIQUE INDEX name (name, not_deleted), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE login_log (id INT UNSIGNED AUTO_INCREMENT NOT NULL, user_id INT UNSIGNED DEFAULT NULL, date DATETIME DEFAULT CURRENT_TIMESTAMP, login VARCHAR(1000) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`, section VARCHAR(255) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`, success TINYINT(1) NOT NULL, msg VARCHAR(100) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, ip VARCHAR(50) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, user_agent VARCHAR(1000) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, not_deleted TINYINT(1) DEFAULT \'1\', INDEX user_id (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE message (id INT UNSIGNED AUTO_INCREMENT NOT NULL COMMENT \'id\', sender_user_id INT UNSIGNED NOT NULL COMMENT \'odesílatel\', recipient_user_id INT UNSIGNED NOT NULL COMMENT \'příjemce\', text TEXT CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci` COMMENT \'text\', `read` TINYINT(1) DEFAULT \'0\' NOT NULL COMMENT \'přečteno příjemcem\', read_date DATETIME DEFAULT NULL COMMENT \'datum přečtení\', read_by_user_id INT UNSIGNED DEFAULT NULL COMMENT \'přečteno uživatelem\', created DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT \'Vytvořeno\', created_user_id INT UNSIGNED NOT NULL COMMENT \'Vytvořil\', changed DATETIME DEFAULT NULL COMMENT \'Změněno\', changed_user_id INT UNSIGNED DEFAULT NULL COMMENT \'Změnil\', active TINYINT(1) DEFAULT \'1\' NOT NULL COMMENT \'Aktivní\', not_deleted TINYINT(1) DEFAULT \'1\' COMMENT \'Nesmazaný\', INDEX recipient_user_id (recipient_user_id), INDEX sender_user_id (sender_user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'chat\' ');
        $this->addSql('CREATE TABLE notification (id INT UNSIGNED AUTO_INCREMENT NOT NULL COMMENT \'id\', text TEXT CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci` COMMENT \'text\', `read` TINYINT(1) DEFAULT \'0\' NOT NULL COMMENT \'přečteno příjemcem\', read_date DATETIME DEFAULT NULL COMMENT \'datum přečtení\', read_by_user_id INT UNSIGNED DEFAULT NULL COMMENT \'přečteno uživatelem\', created DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT \'Vytvořeno\', created_user_id INT UNSIGNED NOT NULL COMMENT \'Vytvořil\', changed DATETIME DEFAULT NULL COMMENT \'Změněno\', changed_user_id INT UNSIGNED DEFAULT NULL COMMENT \'Změnil\', active TINYINT(1) DEFAULT \'1\' NOT NULL COMMENT \'Aktivní\', not_deleted TINYINT(1) DEFAULT \'1\' COMMENT \'Nesmazaný\', PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'not\' ');
        $this->addSql('CREATE TABLE payment (id INT UNSIGNED AUTO_INCREMENT NOT NULL COMMENT \'Id\', code VARCHAR(50) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_czech_ci` COMMENT \'Kód způsobu platby\', price NUMERIC(10, 2) DEFAULT NULL COMMENT \'Cena\', vat INT UNSIGNED NOT NULL COMMENT \'DPH\', payment_method VARCHAR(127) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_czech_ci` COMMENT \'Metoda online platby, pokud se jedná o online platbu\', online_payment TINYINT(1) DEFAULT \'0\' COMMENT \'Online platba\', not_deleted TINYINT(1) DEFAULT \'1\' COMMENT \'Nesmazaný\', INDEX not_deleted (not_deleted), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE product (id INT UNSIGNED AUTO_INCREMENT NOT NULL COMMENT \'Id\', product_category_id INT UNSIGNED DEFAULT 1 NOT NULL COMMENT \'Kategorie\', language_id TINYINT(1) DEFAULT NULL COMMENT \'Jazyk\', product_availability_id SMALLINT UNSIGNED DEFAULT NULL COMMENT \'Dostupnost\', created_user_id INT UNSIGNED NOT NULL COMMENT \'Vytvořil\', changed_user_id INT UNSIGNED DEFAULT NULL COMMENT \'Změnil\', slug VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci` COMMENT \'Identifikátor\', name VARCHAR(400) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci` COMMENT \'Název\', `desc` TEXT CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci` COMMENT \'Popis\', price NUMERIC(14, 2) DEFAULT NULL COMMENT \'Cena\', vat NUMERIC(4, 2) UNSIGNED DEFAULT NULL COMMENT \'DPH\', price_with_vat NUMERIC(14, 2) DEFAULT NULL COMMENT \'Cena s DPH\', added DATE DEFAULT NULL COMMENT \'Datum přidání\', news TINYINT(1) DEFAULT \'0\' NOT NULL COMMENT \'Novinka\', created DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT \'Vytvořeno\', changed DATETIME DEFAULT NULL COMMENT \'Změněno\', active TINYINT(1) DEFAULT \'1\' NOT NULL COMMENT \'Platný\', not_deleted TINYINT(1) DEFAULT \'1\' COMMENT \'Nesmazaný\', INDEX created_user_id (created_user_id), INDEX language_id (language_id), INDEX product_category_id (product_category_id), FULLTEXT INDEX name_desc (name, `desc`), UNIQUE INDEX slug (slug), INDEX changed_user_id (changed_user_id), INDEX product_availability_id (product_availability_id), FULLTEXT INDEX name (name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE product_availability (id SMALLINT UNSIGNED AUTO_INCREMENT NOT NULL, name VARCHAR(20) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`, class VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'Dostupnost produktu\' ');
        $this->addSql('CREATE TABLE product_category (id INT UNSIGNED AUTO_INCREMENT NOT NULL COMMENT \'Id\', product_category_id INT UNSIGNED DEFAULT 1 COMMENT \'Nadřazená kategorie\', created_user_id INT UNSIGNED NOT NULL COMMENT \'Vytvořil\', changed_user_id INT UNSIGNED DEFAULT NULL COMMENT \'Kdo změnil\', slug VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci` COMMENT \'Identifikátor\', name VARCHAR(200) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci` COMMENT \'Název\', created DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT \'Vytvořeno\', changed DATETIME DEFAULT NULL COMMENT \'Čas úpravy\', active TINYINT(1) DEFAULT \'1\' NOT NULL COMMENT \'Platný\', not_deleted TINYINT(1) DEFAULT \'1\' COMMENT \'Nesmazaný\', INDEX created_user_id (created_user_id), INDEX product_category_id (product_category_id), UNIQUE INDEX name_unique (name, not_deleted), UNIQUE INDEX slug (slug), INDEX changed_user_id (changed_user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE product_image (id INT UNSIGNED AUTO_INCREMENT NOT NULL COMMENT \'Id\', product_id INT UNSIGNED DEFAULT NULL COMMENT \'Produkt\', file_id INT UNSIGNED NOT NULL COMMENT \'Soubor obrázku\', created_user_id INT UNSIGNED NOT NULL COMMENT \'Vytvořil\', changed_user_id INT UNSIGNED DEFAULT NULL COMMENT \'Změnil\', name VARCHAR(100) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci` COMMENT \'Název obrázku\', `desc` TEXT CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci` COMMENT \'Popis obrázku\', main TINYINT(1) DEFAULT \'0\' NOT NULL COMMENT \'Hlavní\', `order` INT UNSIGNED NOT NULL COMMENT \'Pořadí\', form_random_string VARCHAR(100) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci` COMMENT \'náhodný řetězec ze skrytého pole\', created DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT \'Vytvořeno\', changed DATETIME DEFAULT NULL COMMENT \'Změněno\', active TINYINT(1) DEFAULT \'1\' NOT NULL COMMENT \'Platný\', not_deleted TINYINT(1) DEFAULT \'1\' COMMENT \'Nesmazaný\', INDEX user_id (created_user_id), INDEX file_id (file_id), INDEX product_id (product_id), INDEX changed_user_id (changed_user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE redirect (id INT UNSIGNED AUTO_INCREMENT NOT NULL, old_url VARCHAR(255) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci` COMMENT \'Zdrojové URL\', url VARCHAR(255) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci` COMMENT \'Nové url\', code CHAR(3) CHARACTER SET utf8 DEFAULT \'301\' NOT NULL COLLATE `utf8_general_ci` COMMENT \'Kód přesměrování\', hits INT UNSIGNED DEFAULT 0 NOT NULL COMMENT \'Počet použití\', extra TINYINT(1) DEFAULT \'0\' NOT NULL COMMENT \'Extra sitemap\', created DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT \'Vytvořeno\', not_deleted TINYINT(1) DEFAULT \'1\' COMMENT \'Smazáno\', UNIQUE INDEX old_url (old_url, not_deleted), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'Přesměrování\' ');
        $this->addSql('CREATE TABLE role (id INT UNSIGNED AUTO_INCREMENT NOT NULL COMMENT \'id\', created_user_id INT UNSIGNED NOT NULL COMMENT \'Vytvořil\', changed_user_id INT UNSIGNED DEFAULT NULL COMMENT \'Kdo změnil\', name VARCHAR(100) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci` COMMENT \'systémový název role\', title VARCHAR(255) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci` COMMENT \'název role\', `desc` TEXT CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci` COMMENT \'popis\', created DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT \'vytvořeno\', changed DATETIME DEFAULT NULL COMMENT \'Čas úpravy\', active TINYINT(1) DEFAULT \'1\' NOT NULL COMMENT \'Platný\', not_deleted TINYINT(1) DEFAULT \'1\' COMMENT \'Nesmazaný\', INDEX created_user_id (created_user_id), UNIQUE INDEX name (name), INDEX changed_user_id (changed_user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE rtgrid_state (id VARCHAR(40) CHARACTER SET utf8 DEFAULT \'\' NOT NULL COLLATE `utf8_czech_ci`, user_id INT UNSIGNED DEFAULT 0 NOT NULL, package LONGTEXT CHARACTER SET utf8 NOT NULL COLLATE `utf8_czech_ci`, PRIMARY KEY(id, user_id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE settings (id INT UNSIGNED AUTO_INCREMENT NOT NULL, `key` VARCHAR(100) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`, value MEDIUMTEXT CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, not_deleted TINYINT(1) DEFAULT \'1\', PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE shipping (id INT UNSIGNED AUTO_INCREMENT NOT NULL COMMENT \'Id\', code VARCHAR(50) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_czech_ci` COMMENT \'Kód způsobu doručení\', price NUMERIC(10, 0) DEFAULT NULL COMMENT \'Cena\', vat INT UNSIGNED NOT NULL COMMENT \'DPH\', free_transport_limit NUMERIC(10, 0) DEFAULT NULL COMMENT \'Minimální částka na dopravu zdarma\', weight_limit INT DEFAULT NULL COMMENT \'Maximální možná váha objednávky pro dopravu v gramech\', shipping_method VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_czech_ci` COMMENT \'Metoda doručení\', not_deleted TINYINT(1) DEFAULT \'1\' COMMENT \'Nesmazáno\', PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE state (id SMALLINT UNSIGNED AUTO_INCREMENT NOT NULL COMMENT \'id\', shortcut VARCHAR(2) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci` COMMENT \'zkratka\', name VARCHAR(100) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci` COMMENT \'název\', phone VARCHAR(5) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci` COMMENT \'tel. předvolba\', vat NUMERIC(3, 1) DEFAULT NULL COMMENT \'DPH\', not_deleted TINYINT(1) DEFAULT \'1\' COMMENT \'aktivní\', UNIQUE INDEX shortcut (shortcut), UNIQUE INDEX name (name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'státy\' ');
        $this->addSql('CREATE TABLE user (id INT UNSIGNED AUTO_INCREMENT NOT NULL COMMENT \'id\', created_user_id INT UNSIGNED DEFAULT NULL COMMENT \'Vytvořil\', changed_user_id INT UNSIGNED DEFAULT NULL COMMENT \'Kdo změnil\', login VARCHAR(64) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci` COMMENT \'login\', password VARCHAR(64) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci` COMMENT \'heslo\', firstname VARCHAR(100) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci` COMMENT \'jméno\', fullname VARCHAR(200) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, lastname VARCHAR(100) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci` COMMENT \'příjmení\', email VARCHAR(200) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci` COMMENT \'email\', login_type VARCHAR(255) CHARACTER SET utf8 DEFAULT \'normal\' NOT NULL COLLATE `utf8_general_ci` COMMENT \'typ přihlášení\', oauth_id VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci` COMMENT \'id uživatele přihlášeného z externí služby google/facebook/linkedin\', external_avatar_url VARCHAR(1000) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci` COMMENT \'URL avataru z přihlášení třetí stranou\', activated DATETIME DEFAULT NULL COMMENT \'datum a čas aktivace\', secret VARCHAR(50) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci` COMMENT \'Tajný kód pro 2FA\', recovery_codes VARCHAR(169) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci` COMMENT \'Záložní kódy pro 2FA\', created DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT \'datum a čas vytvoření\', changed DATETIME DEFAULT NULL COMMENT \'Čas úpravy\', active TINYINT(1) DEFAULT \'1\' NOT NULL COMMENT \'Platný\', not_deleted TINYINT(1) DEFAULT \'1\' COMMENT \'Nesmazaný\', INDEX changed_user_id (changed_user_id), UNIQUE INDEX login_unique (login, not_deleted), UNIQUE INDEX email_unique (email, not_deleted), INDEX created_user_id (created_user_id), FULLTEXT INDEX fullname (fullname), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE user_role (id INT UNSIGNED AUTO_INCREMENT NOT NULL, user_id INT UNSIGNED NOT NULL, role_id INT UNSIGNED NOT NULL, not_deleted TINYINT(1) DEFAULT \'1\', INDEX fk_user_role_role1_idx (role_id), INDEX fk_user_role_user1_idx (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('ALTER TABLE article_tag ADD CONSTRAINT article_tag_article_id FOREIGN KEY (article_id) REFERENCES article (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE article_tag ADD CONSTRAINT article_tag_tag_id FOREIGN KEY (tag_id) REFERENCES tag (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE author ADD CONSTRAINT author_ibfk_1 FOREIGN KEY (changed_user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE author ADD CONSTRAINT author_ibfk_2 FOREIGN KEY (created_user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE author ADD CONSTRAINT author_ibfk_3 FOREIGN KEY (image_file_id) REFERENCES file (id)');
        $this->addSql('ALTER TABLE author_in_product ADD CONSTRAINT FK_author_in_product_author FOREIGN KEY (author_id) REFERENCES author (id) ON UPDATE CASCADE');
        $this->addSql('ALTER TABLE author_in_product ADD CONSTRAINT FK_author_in_product_product FOREIGN KEY (product_id) REFERENCES product (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE bank_code ADD CONSTRAINT bank_code_ibfk_1 FOREIGN KEY (created_user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE bank_code ADD CONSTRAINT bank_code_ibfk_2 FOREIGN KEY (changed_user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE customer ADD CONSTRAINT customer_ibfk_1 FOREIGN KEY (state_id) REFERENCES state (id)');
        $this->addSql('ALTER TABLE customer ADD CONSTRAINT customer_ibfk_2 FOREIGN KEY (created_user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE customer ADD CONSTRAINT customer_ibfk_3 FOREIGN KEY (changed_user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE customer2 ADD CONSTRAINT customer2_ibfk_1 FOREIGN KEY (state_id) REFERENCES state (id)');
        $this->addSql('ALTER TABLE history ADD CONSTRAINT history_ibfk_1 FOREIGN KEY (created_user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE history_data ADD CONSTRAINT history_data_ibfk_1 FOREIGN KEY (history_id) REFERENCES history (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE invoice ADD CONSTRAINT invoice_customer_ibfk_1 FOREIGN KEY (customer_id) REFERENCES customer (id)');
        $this->addSql('ALTER TABLE invoice_delivery ADD CONSTRAINT invoice_delivery_ibfk_1 FOREIGN KEY (invoice_id) REFERENCES invoice (id)');
        $this->addSql('ALTER TABLE invoice_product ADD CONSTRAINT invoice_product_ibfk_1 FOREIGN KEY (invoice_id) REFERENCES invoice (id)');
        $this->addSql('ALTER TABLE invoice_product ADD CONSTRAINT invoice_product_ibfk_2 FOREIGN KEY (created_user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE invoice_product ADD CONSTRAINT invoice_product_ibfk_3 FOREIGN KEY (product_id) REFERENCES product (id)');
        $this->addSql('ALTER TABLE login_log ADD CONSTRAINT login_log_ibfk_1 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE message ADD CONSTRAINT message_ibfk_1 FOREIGN KEY (sender_user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE message ADD CONSTRAINT message_ibfk_2 FOREIGN KEY (recipient_user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE product ADD CONSTRAINT product_ibfk_1 FOREIGN KEY (created_user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE product ADD CONSTRAINT product_ibfk_2 FOREIGN KEY (changed_user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE product ADD CONSTRAINT product_ibfk_3 FOREIGN KEY (language_id) REFERENCES language (id)');
        $this->addSql('ALTER TABLE product ADD CONSTRAINT product_ibfk_4 FOREIGN KEY (product_availability_id) REFERENCES product_availability (id)');
        $this->addSql('ALTER TABLE product ADD CONSTRAINT product_ibfk_5 FOREIGN KEY (product_category_id) REFERENCES product_category (id)');
        $this->addSql('ALTER TABLE product_category ADD CONSTRAINT product_category_ibfk_1 FOREIGN KEY (created_user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE product_category ADD CONSTRAINT product_category_ibfk_2 FOREIGN KEY (changed_user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE product_category ADD CONSTRAINT product_category_ibfk_3 FOREIGN KEY (product_category_id) REFERENCES product_category (id)');
        $this->addSql('ALTER TABLE product_image ADD CONSTRAINT product_image_ibfk_1 FOREIGN KEY (product_id) REFERENCES product (id)');
        $this->addSql('ALTER TABLE product_image ADD CONSTRAINT product_image_ibfk_2 FOREIGN KEY (created_user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE product_image ADD CONSTRAINT product_image_ibfk_3 FOREIGN KEY (changed_user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE product_image ADD CONSTRAINT product_image_ibfk_4 FOREIGN KEY (file_id) REFERENCES file (id)');
        $this->addSql('ALTER TABLE role ADD CONSTRAINT role_ibfk_1 FOREIGN KEY (created_user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE role ADD CONSTRAINT role_ibfk_2 FOREIGN KEY (changed_user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE user ADD CONSTRAINT user_ibfk_1 FOREIGN KEY (created_user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE user ADD CONSTRAINT user_ibfk_2 FOREIGN KEY (changed_user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE user_role ADD CONSTRAINT fk_user_role_role1 FOREIGN KEY (role_id) REFERENCES role (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE user_role ADD CONSTRAINT fk_user_role_user1 FOREIGN KEY (user_id) REFERENCES user (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('DROP TABLE book');
        $this->addSql('DROP TABLE category');
        $this->addSql('DROP TABLE ext_log_entries');
        $this->addSql('DROP TABLE ext_translations');
        $this->addSql('DROP TABLE tag_book');
        $this->addSql('ALTER TABLE article DROP FOREIGN KEY FK_23A0E6612469DE2');
        $this->addSql('DROP INDEX IDX_23A0E6612469DE2 ON article');
        $this->addSql('ALTER TABLE article ADD article_category_id INT UNSIGNED DEFAULT 1 NOT NULL COMMENT \'Kategorie\', ADD created_user_id INT UNSIGNED NOT NULL COMMENT \'Id uživatele, který vytvořil článek\', ADD changed_user_id INT UNSIGNED DEFAULT NULL COMMENT \'Kdo změnil\', ADD intro TEXT CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci` COMMENT \'Úvodní text\', ADD text MEDIUMTEXT CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci` COMMENT \'Hlavní text\', ADD valid_from DATETIME NOT NULL COMMENT \'Publikováno od\', ADD valid_to DATETIME DEFAULT NULL COMMENT \'Publikováno do\', ADD changed DATETIME DEFAULT NULL COMMENT \'Čas úpravy\', ADD active TINYINT(1) DEFAULT \'1\' NOT NULL COMMENT \'Platný\', ADD not_deleted TINYINT(1) DEFAULT \'1\' COMMENT \'Nesmazaný\', DROP category_id, DROP content, DROP updated, DROP content_changed, DROP deletedAt, CHANGE id id INT UNSIGNED AUTO_INCREMENT NOT NULL COMMENT \'Primární klíč\', CHANGE title title VARCHAR(100) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci` COMMENT \'Nadpis článku\', CHANGE slug slug VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_czech_ci` COMMENT \'Identifikátor\', CHANGE created created DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT \'Čas vytvoření\'');
        $this->addSql('ALTER TABLE article ADD CONSTRAINT article_ibfk_1 FOREIGN KEY (changed_user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE article ADD CONSTRAINT article_ibfk_2 FOREIGN KEY (created_user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE article ADD CONSTRAINT article_ibfk_3 FOREIGN KEY (article_category_id) REFERENCES article_category (id)');
        $this->addSql('CREATE INDEX changed_user_id ON article (changed_user_id)');
        $this->addSql('CREATE INDEX article_category_id ON article (article_category_id)');
        $this->addSql('CREATE INDEX created_user_id ON article (created_user_id)');
        $this->addSql('ALTER TABLE article RENAME INDEX uniq_23a0e66989d9b62 TO slug');
        $this->addSql('ALTER TABLE article_category DROP FOREIGN KEY FK_53A4EDAAA977936C');
        $this->addSql('ALTER TABLE article_category DROP FOREIGN KEY FK_53A4EDAA727ACA70');
        $this->addSql('DROP INDEX IDX_53A4EDAAA977936C ON article_category');
        $this->addSql('DROP INDEX IDX_53A4EDAA727ACA70 ON article_category');
        $this->addSql('ALTER TABLE article_category ADD article_category_id INT UNSIGNED DEFAULT 1 COMMENT \'Nadřazená kategorie\', ADD created_user_id INT UNSIGNED NOT NULL COMMENT \'Vytvořil\', ADD changed_user_id INT UNSIGNED DEFAULT NULL COMMENT \'Kdo změnil\', ADD slug VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci` COMMENT \'Identifikátor\', ADD name VARCHAR(50) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci` COMMENT \'Jméno kategorie\', ADD created DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT \'Vytvořeno\', ADD changed DATETIME DEFAULT NULL COMMENT \'Čas úpravy\', ADD active TINYINT(1) DEFAULT \'1\' NOT NULL COMMENT \'Platný\', ADD not_deleted TINYINT(1) DEFAULT \'1\' COMMENT \'Nesmazaný\', DROP tree_root, DROP parent_id, DROP title, DROP lft, DROP lvl, DROP rgt, CHANGE id id INT UNSIGNED AUTO_INCREMENT NOT NULL COMMENT \'Primární klíč\'');
        $this->addSql('ALTER TABLE article_category ADD CONSTRAINT article_category_ibfk_1 FOREIGN KEY (created_user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE article_category ADD CONSTRAINT article_category_ibfk_2 FOREIGN KEY (changed_user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE article_category ADD CONSTRAINT article_category_ibfk_3 FOREIGN KEY (article_category_id) REFERENCES article_category (id)');
        $this->addSql('CREATE INDEX created_user_id ON article_category (created_user_id)');
        $this->addSql('CREATE INDEX article_category_id ON article_category (article_category_id)');
        $this->addSql('CREATE UNIQUE INDEX name_unique ON article_category (name, not_deleted)');
        $this->addSql('CREATE UNIQUE INDEX slug ON article_category (slug)');
        $this->addSql('CREATE INDEX changed_user_id ON article_category (changed_user_id)');
        $this->addSql('ALTER TABLE tag ADD created_user_id INT UNSIGNED DEFAULT NULL COMMENT \'Vytvořil\', ADD changed_user_id INT UNSIGNED DEFAULT NULL COMMENT \'Kdo změnil\', ADD name VARCHAR(50) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci` COMMENT \'Jméno tagu\', ADD created DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT \'datum a čas vytvoření\', ADD changed DATETIME DEFAULT NULL COMMENT \'Čas úpravy\', ADD active TINYINT(1) DEFAULT \'1\' NOT NULL COMMENT \'Platný\', ADD not_deleted TINYINT(1) DEFAULT \'1\' COMMENT \'Nesmazaný\', DROP title, CHANGE id id INT UNSIGNED AUTO_INCREMENT NOT NULL COMMENT \'Primární klíč\'');
        $this->addSql('ALTER TABLE tag ADD CONSTRAINT tag_ibfk_1 FOREIGN KEY (created_user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE tag ADD CONSTRAINT tag_ibfk_2 FOREIGN KEY (changed_user_id) REFERENCES user (id)');
        $this->addSql('CREATE INDEX changed_user_id ON tag (changed_user_id)');
        $this->addSql('CREATE INDEX created_user_id ON tag (created_user_id)');
    }
}
